# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-03 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_tasklog_tasklogdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='task_type',
            field=models.CharField(choices=[(b'multi_cmd', b'CMD'), (b'file_send', b'\xe6\x89\xb9\xe9\x87\x8f\xe5\x8f\x91\xe9\x80\x81\xe6\x96\x87\xe4\xbb\xb6'), (b'file_get', b'\xe6\x89\xb9\xe9\x87\x8f\xe4\xb8\x8b\xe8\xbd\xbd\xe6\x96\x87\xe4\xbb\xb6')], max_length=50),
        ),
    ]
